apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: django-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: angular-web-app
        image: devacr83.azurecr.io/python-repo/django-app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
      
---
apiVersion: v1
kind: Service
metadata:
  name: django-app
spec:
  type: LoadBalancer
  ports: